[Seat:*]
session-setup-script=/usr/libexec/etakit-kilit-session-setup
session-cleanup-script=/usr/libexec/etakit-kilit-session-cleanup
greeter-setup-script=/usr/libexec/etakit-kilit-session-greeter

[SeatDefaults]
session-setup-script=/usr/libexec/etakit-kilit-session-setup
session-cleanup-script=/usr/libexec/etakit-kilit-session-cleanup
greeter-setup-script=/usr/libexec/etakit-kilit-session-greeter
