#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
    rm -rf /var/lib/etakit
fi

if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database /usr/share/applications >/dev/null 2>&1 || true
fi

exit 0
